import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/nav";
import Footer from "@/components/layout/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section>
          <div className="fixed w-full z-10 bg-white ">
            <Navbar />
          </div>
          <div>{children}</div>
          <div>
            <Footer />
          </div>
        </section>
      </body>
    </html>
  );
}
